/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XTools {

public class DiscoveredSystem : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DiscoveredSystem(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DiscoveredSystem obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DiscoveredSystem() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XToolsProfilerPINVOKE.delete_DiscoveredSystem(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public DiscoveredSystem(string name, string address, SystemRole role) : this(XToolsProfilerPINVOKE.new_DiscoveredSystem(name, address, (int)role), true) {
    if (XToolsProfilerPINVOKE.SWIGPendingException.Pending) throw XToolsProfilerPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetName() {
    string ret = XToolsProfilerPINVOKE.DiscoveredSystem_GetName(swigCPtr);
    return ret;
  }

  public string GetAddress() {
    string ret = XToolsProfilerPINVOKE.DiscoveredSystem_GetAddress(swigCPtr);
    return ret;
  }

  public SystemRole GetRole() {
    SystemRole ret = (SystemRole)XToolsProfilerPINVOKE.DiscoveredSystem_GetRole(swigCPtr);
    return ret;
  }

}

}
