/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XTools {

public class ProfileSample : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ProfileSample(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ProfileSample obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ProfileSample() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XToolsProfilerPINVOKE.delete_ProfileSample(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ProfileSample(string name, ulong startTime, ulong duration, int parentIndex) : this(XToolsProfilerPINVOKE.new_ProfileSample(name, startTime, duration, parentIndex), true) {
    if (XToolsProfilerPINVOKE.SWIGPendingException.Pending) throw XToolsProfilerPINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetName() {
    string ret = XToolsProfilerPINVOKE.ProfileSample_GetName(swigCPtr);
    return ret;
  }

  public ulong GetStartTime() {
    ulong ret = XToolsProfilerPINVOKE.ProfileSample_GetStartTime(swigCPtr);
    return ret;
  }

  public ulong GetDuration() {
    ulong ret = XToolsProfilerPINVOKE.ProfileSample_GetDuration(swigCPtr);
    return ret;
  }

  public int GetParentIndex() {
    int ret = XToolsProfilerPINVOKE.ProfileSample_GetParentIndex(swigCPtr);
    return ret;
  }

}

}
