/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XTools {

public class XString : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal XString(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(XString obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~XString() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XToolsProfilerPINVOKE.delete_XString(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public XString() : this(XToolsProfilerPINVOKE.new_XString__SWIG_0(), true) {
  }

  public XString(string str) : this(XToolsProfilerPINVOKE.new_XString__SWIG_1(str), true) {
    if (XToolsProfilerPINVOKE.SWIGPendingException.Pending) throw XToolsProfilerPINVOKE.SWIGPendingException.Retrieve();
  }

  public uint GetLength() {
    uint ret = XToolsProfilerPINVOKE.XString_GetLength(swigCPtr);
    return ret;
  }

  public bool IsEqual(XString otherStr) {
    bool ret = XToolsProfilerPINVOKE.XString_IsEqual(swigCPtr, XString.getCPtr(otherStr));
    return ret;
  }

  public string GetString() {
    string ret = XToolsProfilerPINVOKE.XString_GetString(swigCPtr);
    return ret;
  }

}

}
