/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace XTools {

public class XToolsProfiler {
  public static ulong kInvalidSocketID {
    get {
      ulong ret = XToolsProfilerPINVOKE.kInvalidSocketID_get();
      return ret;
    } 
  }

  public static ulong kInvalidConnectionGUID {
    get {
      ulong ret = XToolsProfilerPINVOKE.kInvalidConnectionGUID_get();
      return ret;
    } 
  }

}

}
