/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_XToolsClient_WRAP_H_
#define SWIG_XToolsClient_WRAP_H_

class SwigDirector_LogWriter : public XTools::LogWriter, public Swig::Director {

public:
    SwigDirector_LogWriter();
    virtual ~SwigDirector_LogWriter();
    virtual void WriteLogEntry(XTools::LogSeverity severity, std::string const &message);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(int, char *);
    void swig_connect_director(SWIG_Callback0_t callbackWriteLogEntry);

private:
    SWIG_Callback0_t swig_callbackWriteLogEntry;
    void swig_init_callbacks();
};

class SwigDirector_NetworkConnectionListener : public XTools::NetworkConnectionListener, public Swig::Director {

public:
    SwigDirector_NetworkConnectionListener();
    virtual ~SwigDirector_NetworkConnectionListener();
    virtual void OnConnected(XTools::NetworkConnectionPtr const &connection);
    virtual void OnConnectFailed(XTools::NetworkConnectionPtr const &connection);
    virtual void OnDisconnected(XTools::NetworkConnectionPtr const &connection);
    virtual void OnMessageReceived(XTools::NetworkConnectionPtr const &connection, XTools::NetworkInMessage &message);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *, void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnConnected, SWIG_Callback1_t callbackOnConnectFailed, SWIG_Callback2_t callbackOnDisconnected, SWIG_Callback3_t callbackOnMessageReceived);

private:
    SWIG_Callback0_t swig_callbackOnConnected;
    SWIG_Callback1_t swig_callbackOnConnectFailed;
    SWIG_Callback2_t swig_callbackOnDisconnected;
    SWIG_Callback3_t swig_callbackOnMessageReceived;
    void swig_init_callbacks();
};

class SwigDirector_ObjectElementListener : public XTools::ObjectElementListener, public Swig::Director {

public:
    SwigDirector_ObjectElementListener();
    virtual ~SwigDirector_ObjectElementListener();
    virtual void OnIntElementChanged(XTools::XGuid elementID, XTools::int32 newValue);
    virtual void OnFloatElementChanged(XTools::XGuid elementID, float newValue);
    virtual void OnStringElementChanged(XTools::XGuid elementID, XTools::XStringPtr const &newValue);
    virtual void OnElementAdded(XTools::ElementPtr const &element);
    virtual void OnElementDeleted(XTools::ElementPtr const &element);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(long long, int);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(long long, float);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(long long, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnIntElementChanged, SWIG_Callback1_t callbackOnFloatElementChanged, SWIG_Callback2_t callbackOnStringElementChanged, SWIG_Callback3_t callbackOnElementAdded, SWIG_Callback4_t callbackOnElementDeleted);

private:
    SWIG_Callback0_t swig_callbackOnIntElementChanged;
    SWIG_Callback1_t swig_callbackOnFloatElementChanged;
    SWIG_Callback2_t swig_callbackOnStringElementChanged;
    SWIG_Callback3_t swig_callbackOnElementAdded;
    SWIG_Callback4_t swig_callbackOnElementDeleted;
    void swig_init_callbacks();
};

class SwigDirector_SyncListener : public XTools::SyncListener, public Swig::Director {

public:
    SwigDirector_SyncListener();
    virtual ~SwigDirector_SyncListener();
    virtual void OnSyncChangesBegin();
    virtual void OnSyncChangesEnd();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackOnSyncChangesBegin, SWIG_Callback1_t callbackOnSyncChangesEnd);

private:
    SWIG_Callback0_t swig_callbackOnSyncChangesBegin;
    SWIG_Callback1_t swig_callbackOnSyncChangesEnd;
    void swig_init_callbacks();
};

class SwigDirector_SessionListener : public XTools::SessionListener, public Swig::Director {

public:
    SwigDirector_SessionListener();
    virtual ~SwigDirector_SessionListener();
    virtual void OnJoiningSession();
    virtual void OnJoinSucceeded();
    virtual void OnJoinFailed();
    virtual void OnSessionDisconnected();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)();
    void swig_connect_director(SWIG_Callback0_t callbackOnJoiningSession, SWIG_Callback1_t callbackOnJoinSucceeded, SWIG_Callback2_t callbackOnJoinFailed, SWIG_Callback3_t callbackOnSessionDisconnected);

private:
    SWIG_Callback0_t swig_callbackOnJoiningSession;
    SWIG_Callback1_t swig_callbackOnJoinSucceeded;
    SWIG_Callback2_t swig_callbackOnJoinFailed;
    SWIG_Callback3_t swig_callbackOnSessionDisconnected;
    void swig_init_callbacks();
};

class SwigDirector_SessionManagerListener : public XTools::SessionManagerListener, public Swig::Director {

public:
    SwigDirector_SessionManagerListener();
    virtual ~SwigDirector_SessionManagerListener();
    virtual void OnCreateSucceeded(XTools::SessionPtr const &newSession);
    virtual void OnCreateFailed(XTools::XStringPtr const &reason);
    virtual void OnSessionAdded(XTools::SessionPtr const &newSession);
    virtual void OnSessionClosed(XTools::SessionPtr const &session);
    virtual void OnUserJoinedSession(XTools::SessionPtr const &session, XTools::UserPtr const &newUser);
    virtual void OnUserLeftSession(XTools::SessionPtr const &session, XTools::UserPtr const &user);
    virtual void OnUserChanged(XTools::SessionPtr const &session, XTools::UserPtr const &user);
    virtual void OnServerConnected();
    virtual void OnServerDisconnected();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback2_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback3_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback5_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback6_t)(void *, void *);
    typedef void (SWIGSTDCALL* SWIG_Callback7_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback8_t)();
    void swig_connect_director(SWIG_Callback0_t callbackOnCreateSucceeded, SWIG_Callback1_t callbackOnCreateFailed, SWIG_Callback2_t callbackOnSessionAdded, SWIG_Callback3_t callbackOnSessionClosed, SWIG_Callback4_t callbackOnUserJoinedSession, SWIG_Callback5_t callbackOnUserLeftSession, SWIG_Callback6_t callbackOnUserChanged, SWIG_Callback7_t callbackOnServerConnected, SWIG_Callback8_t callbackOnServerDisconnected);

private:
    SWIG_Callback0_t swig_callbackOnCreateSucceeded;
    SWIG_Callback1_t swig_callbackOnCreateFailed;
    SWIG_Callback2_t swig_callbackOnSessionAdded;
    SWIG_Callback3_t swig_callbackOnSessionClosed;
    SWIG_Callback4_t swig_callbackOnUserJoinedSession;
    SWIG_Callback5_t swig_callbackOnUserLeftSession;
    SWIG_Callback6_t swig_callbackOnUserChanged;
    SWIG_Callback7_t swig_callbackOnServerConnected;
    SWIG_Callback8_t swig_callbackOnServerDisconnected;
    void swig_init_callbacks();
};

class SwigDirector_UserPresenceManagerListener : public XTools::UserPresenceManagerListener, public Swig::Director {

public:
    SwigDirector_UserPresenceManagerListener();
    virtual ~SwigDirector_UserPresenceManagerListener();
    virtual void OnUserPresenceChanged(XTools::UserPtr const &user);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    void swig_connect_director(SWIG_Callback0_t callbackOnUserPresenceChanged);

private:
    SWIG_Callback0_t swig_callbackOnUserPresenceChanged;
    void swig_init_callbacks();
};

class SwigDirector_PairMaker : public XTools::PairMaker, public Swig::Director {

public:
    SwigDirector_PairMaker();
    virtual ~SwigDirector_PairMaker();
    virtual bool IsReceiver();
    virtual XTools::int32 GetAddressCount();
    virtual XTools::XStringPtr GetAddress(XTools::int32 index);
    virtual XTools::uint16 GetPort();
    virtual void Update();
    virtual bool IsReadyToConnect();
    virtual XTools::int32 GetLocalKey();
    virtual XTools::int32 GetRemoteKey();

    typedef unsigned int (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback1_t)();
    typedef void * (SWIGSTDCALL* SWIG_Callback2_t)(int);
    typedef unsigned short (SWIGSTDCALL* SWIG_Callback3_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback4_t)();
    typedef unsigned int (SWIGSTDCALL* SWIG_Callback5_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback6_t)();
    typedef int (SWIGSTDCALL* SWIG_Callback7_t)();
    void swig_connect_director(SWIG_Callback0_t callbackIsReceiver, SWIG_Callback1_t callbackGetAddressCount, SWIG_Callback2_t callbackGetAddress, SWIG_Callback3_t callbackGetPort, SWIG_Callback4_t callbackUpdate, SWIG_Callback5_t callbackIsReadyToConnect, SWIG_Callback6_t callbackGetLocalKey, SWIG_Callback7_t callbackGetRemoteKey);

private:
    SWIG_Callback0_t swig_callbackIsReceiver;
    SWIG_Callback1_t swig_callbackGetAddressCount;
    SWIG_Callback2_t swig_callbackGetAddress;
    SWIG_Callback3_t swig_callbackGetPort;
    SWIG_Callback4_t swig_callbackUpdate;
    SWIG_Callback5_t swig_callbackIsReadyToConnect;
    SWIG_Callback6_t swig_callbackGetLocalKey;
    SWIG_Callback7_t swig_callbackGetRemoteKey;
    void swig_init_callbacks();
};

class SwigDirector_PairingListener : public XTools::PairingListener, public Swig::Director {

public:
    SwigDirector_PairingListener();
    virtual ~SwigDirector_PairingListener();
    virtual void PairingConnectionSucceeded();
    virtual void PairingConnectionFailed(XTools::PairingResult reason);

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)();
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)(int);
    void swig_connect_director(SWIG_Callback0_t callbackPairingConnectionSucceeded, SWIG_Callback1_t callbackPairingConnectionFailed);

private:
    SWIG_Callback0_t swig_callbackPairingConnectionSucceeded;
    SWIG_Callback1_t swig_callbackPairingConnectionFailed;
    void swig_init_callbacks();
};

class SwigDirector_ImageTagLocationListener : public XTools::ImageTagLocationListener, public Swig::Director {

public:
    SwigDirector_ImageTagLocationListener();
    virtual ~SwigDirector_ImageTagLocationListener();
    virtual void OnTagLocated(XTools::ImageTagLocationPtr const &location);
    virtual void OnTagLocatingCompleted();

    typedef void (SWIGSTDCALL* SWIG_Callback0_t)(void *);
    typedef void (SWIGSTDCALL* SWIG_Callback1_t)();
    void swig_connect_director(SWIG_Callback0_t callbackOnTagLocated, SWIG_Callback1_t callbackOnTagLocatingCompleted);

private:
    SWIG_Callback0_t swig_callbackOnTagLocated;
    SWIG_Callback1_t swig_callbackOnTagLocatingCompleted;
    void swig_init_callbacks();
};


#endif
