# This Yaml Document has been converted by ESAI Yaml Pipeline Conversion Tool.
# Please make sure to check all the converted content, it is your team's responsibility to make sure that the pipeline is still valid and functions as expected.
# This pipeline will be extended to the OneESPT template
# The pool section has been filled with placeholder values, replace the pool section with your hosted pool, os, and image name. If you are using a Linux image, you must specify an additional windows image for SDL: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/overview#how-to-specify-a-windows-pool-for-the-sdl-source-analysis-stage
parameters:
- name: ProjectFriendlyName
  type: string
  default: ''
- name: SolutionPath
  type: string
  default: ''
- name: BuildOutputPath
  type: string
  default: ''
- name: UnityFolderPath
  type: string
  default: ''
- name: BuildVmImage
  type: string
  default: windows-2022
- name: Architectures
  type: object
  default: [x86, x64, ARM, ARM64]
- name: Sign
  type: boolean
  default: false
variables:
  BuildConfiguration: Release
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release
extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: 1ESPT-Pool-Name-Placeholder
      image: pool-image-placeholder
      os: windows
    customBuildTags:
    - ES365AIMigrationTooling
    stages:
    - stage: stage
      jobs:
      - job: Build_${{ parameters.ProjectFriendlyName }}
        strategy:
          matrix:
            ${{ each arch in parameters.Architectures }}:
              ${{ arch }}:
                BuildPlatform: ${{ arch }}
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish artifacts'
            artifactName: ${{ parameters.ArtifactName }}
        steps:
        - template: /CI/Templates/Tasks/build.yml@self
          parameters:
            ArtifactName: ${{ parameters.ProjectFriendlyName }}
            SolutionPath: ${{ parameters.SolutionPath }}
            BuildOutputPath: ${{ parameters.BuildOutputPath }}
      - job: Pack_and_Sign_${{ parameters.Sign }}
        dependsOn: Build_${{ parameters.ProjectFriendlyName }}
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish UPM folder'
            targetPath: ${{ parameters.UnityFolderPath }}
            artifactName: ${{ parameters.UploadFolderArtifactName }}
          - output: pipelineArtifact
            displayName: 'Publish UPM artifacts'
            artifactName: ${{ parameters.UploadTarballArtifactName }}
        steps:
        - template: /CI/Templates/Tasks/pack.yml@self
          parameters:
            DownloadArtifactName: ${{ parameters.ProjectFriendlyName }}
            UnityFolderPath: ${{ parameters.UnityFolderPath }}
            Sign: ${{ parameters.Sign }}