parameters:
- name: ProjectFriendlyName
  type: string
  default: ''
- name: SolutionPath
  type: string
  default: ''
- name: BuildOutputPath
  type: string
  default: ''
- name: UnityFolderPath
  type: string
  default: ''
- name: Sign
  type: boolean
  default: false

variables:
  BuildConfiguration: Release

jobs:
- job: Build_${{ parameters.ProjectFriendlyName }}
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      ${{ if contains(parameters.BuildPlatforms, 'x86' )}}
        x86:
          BuildPlatform: x86
      ${{ if contains(parameters.BuildPlatforms, 'x64' )}}
        x64:
          BuildPlatform: x64
      ${{ if contains(parameters.BuildPlatforms, 'ARM' )}}
        ARM:
          BuildPlatform: ARM
      ${{ if contains(parameters.BuildPlatforms, 'ARM64' )}}
        ARM64:
          BuildPlatform: ARM64
  steps:
  - template: Tasks/build.yml
    parameters:
      ArtifactName: ${{ parameters.ProjectFriendlyName }}
      SolutionPath: ${{ parameters.SolutionPath }}
      BuildOutputPath: ${{ parameters.BuildOutputPath }}

- job: Pack_and_Sign_${{ parameters.Sign }}
  dependsOn: Build_${{ parameters.ProjectFriendlyName }}
  pool:
    name: EDT-1ES-WindowsLatest
  steps:
  - template: Tasks/pack.yml
    parameters:
      DownloadArtifactName: ${{ parameters.ProjectFriendlyName }}
      UnityFolderPath: ${{ parameters.UnityFolderPath }}
      Sign: ${{ parameters.Sign }}
