parameters:
- name: ProjectFriendlyName
  type: string
  default: ''
- name: SolutionPath
  type: string
  default: ''
- name: BuildOutputPath
  type: string
  default: ''
- name: UnityFolderPath
  type: string
  default: ''
- name: Sign
  type: boolean
  default: false

variables:
  BuildConfiguration: Release

jobs:
- job: Build_${{ parameters.ProjectFriendlyName }}
  pool:
    name: EDT-1ES-WindowsLatest
  strategy:
    matrix:
      x86:
        BuildPlatform: x86
      x64:
        BuildPlatform: x64
      ARM:
        BuildPlatform: ARM
      ARM64:
        BuildPlatform: ARM64
  steps:
  - template: Tasks/build.yml
    parameters:
      ArtifactName: ${{ parameters.ProjectFriendlyName }}
      SolutionPath: ${{ parameters.SolutionPath }}
      BuildOutputPath: ${{ parameters.BuildOutputPath }}

- job: Pack_and_Sign_${{ parameters.Sign }}
  dependsOn: Build_${{ parameters.ProjectFriendlyName }}
  pool:
    name: EDT-1ES-WindowsLatest
  steps:
  - template: Tasks/pack.yml
    parameters:
      DownloadArtifactName: ${{ parameters.ProjectFriendlyName }}
      UnityFolderPath: ${{ parameters.UnityFolderPath }}
      Sign: ${{ parameters.Sign }}
