parameters:
- name: ProjectFriendlyName
  type: string
  default: ''
- name: SolutionPath
  type: string
  default: ''
- name: BuildOutputPath
  type: string
  default: ''
- name: UnityFolderPath
  type: string
  default: ''
- name: Architectures
  type: object
  default: [x86,x64,ARM,ARM64]
- name: Sign
  type: boolean
  default: false

variables:
  BuildConfiguration: Release

jobs:
- job: Build_${{ parameters.ProjectFriendlyName }}
  pool:
    vmImage: windows-2019
  strategy:
    matrix:
      ${{ each arch in parameters.Architectures }}:
        ${{ arch }}:
          BuildPlatform: ${{ arch }}
  steps:
  - template: Tasks/build.yml
    parameters:
      ArtifactName: ${{ parameters.ProjectFriendlyName }}
      SolutionPath: ${{ parameters.SolutionPath }}
      BuildOutputPath: ${{ parameters.BuildOutputPath }}

- job: Pack_and_Sign_${{ parameters.Sign }}
  dependsOn: Build_${{ parameters.ProjectFriendlyName }}
  pool:
    name: EDT-1ES-WindowsLatest
  steps:
  - template: Tasks/pack.yml
    parameters:
      DownloadArtifactName: ${{ parameters.ProjectFriendlyName }}
      UnityFolderPath: ${{ parameters.UnityFolderPath }}
      Sign: ${{ parameters.Sign }}
