/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public enum ClientRole {
  Primary(0),
  Secondary;

  public final int swigValue() {
    return swigValue;
  }

  public static ClientRole swigToEnum(int swigValue) {
    ClientRole[] swigValues = ClientRole.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (ClientRole swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + ClientRole.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private ClientRole() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private ClientRole(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private ClientRole(ClientRole swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

