/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class DirectPairReceiver extends PairMaker {
  private long swigCPtr;

  protected DirectPairReceiver(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.DirectPairReceiver_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DirectPairReceiver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_DirectPairReceiver(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DirectPairReceiver() {
    this(XToolsClientJNI.new_DirectPairReceiver__SWIG_0(), true);
  }

  public DirectPairReceiver(int port) {
    this(XToolsClientJNI.new_DirectPairReceiver__SWIG_1(port), true);
  }

  public boolean IsReceiver() {
    return XToolsClientJNI.DirectPairReceiver_IsReceiver(swigCPtr, this);
  }

  public int GetAddressCount() {
    return XToolsClientJNI.DirectPairReceiver_GetAddressCount(swigCPtr, this);
  }

  public XString GetAddress(int index) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.DirectPairReceiver_GetAddress(swigCPtr, this, index);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

  public int GetPort() {
    return XToolsClientJNI.DirectPairReceiver_GetPort(swigCPtr, this);
  }

  public void Update() {
    XToolsClientJNI.DirectPairReceiver_Update(swigCPtr, this);
  }

  public boolean IsReadyToConnect() {
    return XToolsClientJNI.DirectPairReceiver_IsReadyToConnect(swigCPtr, this);
  }

  public void SetIncomingPort(int port) {
    XToolsClientJNI.DirectPairReceiver_SetIncomingPort(swigCPtr, this, port);
  }

}
