/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class DirectPairConnector extends PairMaker {
  private long swigCPtr;

  protected DirectPairConnector(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.DirectPairConnector_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DirectPairConnector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_DirectPairConnector(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public DirectPairConnector() {
    this(XToolsClientJNI.new_DirectPairConnector__SWIG_0(), true);
  }

  public DirectPairConnector(XString remoteNameOrIP) {
    this(XToolsClientJNI.new_DirectPairConnector__SWIG_1(XString.getCPtr(remoteNameOrIP), remoteNameOrIP), true);
  }

  public DirectPairConnector(XString remoteNameOrIP, int port) {
    this(XToolsClientJNI.new_DirectPairConnector__SWIG_2(XString.getCPtr(remoteNameOrIP), remoteNameOrIP, port), true);
  }

  public boolean IsReceiver() {
    return XToolsClientJNI.DirectPairConnector_IsReceiver(swigCPtr, this);
  }

  public int GetAddressCount() {
    return XToolsClientJNI.DirectPairConnector_GetAddressCount(swigCPtr, this);
  }

  public XString GetAddress(int index) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.DirectPairConnector_GetAddress(swigCPtr, this, index);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

  public int GetPort() {
    return XToolsClientJNI.DirectPairConnector_GetPort(swigCPtr, this);
  }

  public void Update() {
    XToolsClientJNI.DirectPairConnector_Update(swigCPtr, this);
  }

  public boolean IsReadyToConnect() {
    return XToolsClientJNI.DirectPairConnector_IsReadyToConnect(swigCPtr, this);
  }

  public void SetRemoteAddress(XString remoteNameOrIP) {
    XToolsClientJNI.DirectPairConnector_SetRemoteAddress(swigCPtr, this, XString.getCPtr(remoteNameOrIP), remoteNameOrIP);
  }

  public void SetRemotePort(int port) {
    XToolsClientJNI.DirectPairConnector_SetRemotePort(swigCPtr, this, port);
  }

}
