/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class Element {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Element(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Element obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_Element(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ElementType GetElementType() {
    return ElementType.swigToEnum(XToolsClientJNI.Element_GetElementType(swigCPtr, this));
  }

  public long GetGUID() {
    return XToolsClientJNI.Element_GetGUID(swigCPtr, this);
  }

  public XString GetName() {
	// ref_ptr by reference javaout
    long cPtr = XToolsClientJNI.Element_GetName(swigCPtr, this);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

  public Element GetParent() {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.Element_GetParent(swigCPtr, this);
    return (cPtr == 0) ? null : new Element(cPtr, true);
  }

  public boolean IsValid() {
    return XToolsClientJNI.Element_IsValid(swigCPtr, this);
  }

}
