/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class FloatElement extends Element {
  private long swigCPtr;

  protected FloatElement(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.FloatElement_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FloatElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_FloatElement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static FloatElement Cast(Element element) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.FloatElement_Cast(Element.getCPtr(element), element);
    return (cPtr == 0) ? null : new FloatElement(cPtr, true);
  }

  public float GetValue() {
    return XToolsClientJNI.FloatElement_GetValue(swigCPtr, this);
  }

  public void SetValue(float newValue) {
    XToolsClientJNI.FloatElement_SetValue(swigCPtr, this, newValue);
  }

}
