/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class ImageTagManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ImageTagManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageTagManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_ImageTagManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Update() {
    XToolsClientJNI.ImageTagManager_Update(swigCPtr, this);
  }

  public boolean FindTags(byte[] data, int pixelWidth, int pixelHeight, int bytesPerPixel, ImageTagLocationListener locationCallback) {
    return XToolsClientJNI.ImageTagManager_FindTags(swigCPtr, this, data, pixelWidth, pixelHeight, bytesPerPixel, ImageTagLocationListener.getCPtr(locationCallback), locationCallback);
  }

  public TagImage CreateTagImage(int tagId) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ImageTagManager_CreateTagImage(swigCPtr, this, tagId);
    return (cPtr == 0) ? null : new TagImage(cPtr, true);
  }

  public static ImageTagManager Create() {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ImageTagManager_Create();
    return (cPtr == 0) ? null : new ImageTagManager(cPtr, true);
  }

}
