/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class ImageTagLocationListener extends Listener {
  private long swigCPtr;

  protected ImageTagLocationListener(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.ImageTagLocationListener_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ImageTagLocationListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_ImageTagLocationListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XToolsClientJNI.ImageTagLocationListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XToolsClientJNI.ImageTagLocationListener_change_ownership(this, swigCPtr, true);
  }

  public void OnTagLocated(ImageTagLocation location) {
    if (getClass() == ImageTagLocationListener.class) XToolsClientJNI.ImageTagLocationListener_OnTagLocated(swigCPtr, this, ImageTagLocation.getCPtr(location), location); else XToolsClientJNI.ImageTagLocationListener_OnTagLocatedSwigExplicitImageTagLocationListener(swigCPtr, this, ImageTagLocation.getCPtr(location), location);
  }

  public void OnTagLocatingCompleted() {
    if (getClass() == ImageTagLocationListener.class) XToolsClientJNI.ImageTagLocationListener_OnTagLocatingCompleted(swigCPtr, this); else XToolsClientJNI.ImageTagLocationListener_OnTagLocatingCompletedSwigExplicitImageTagLocationListener(swigCPtr, this);
  }

  public ImageTagLocationListener() {
    this(XToolsClientJNI.new_ImageTagLocationListener(), true);
    XToolsClientJNI.ImageTagLocationListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
