/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class IntElement extends Element {
  private long swigCPtr;

  protected IntElement(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.IntElement_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(IntElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_IntElement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static IntElement Cast(Element element) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.IntElement_Cast(Element.getCPtr(element), element);
    return (cPtr == 0) ? null : new IntElement(cPtr, true);
  }

  public int GetValue() {
    return XToolsClientJNI.IntElement_GetValue(swigCPtr, this);
  }

  public void SetValue(int newValue) {
    XToolsClientJNI.IntElement_SetValue(swigCPtr, this, newValue);
  }

}
