/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class Listener {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Listener(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Listener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_Listener(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void UnregisterAll() {
    XToolsClientJNI.Listener_UnregisterAll(swigCPtr, this);
  }

  public boolean IsRegistered() {
    return XToolsClientJNI.Listener_IsRegistered(swigCPtr, this);
  }

  public Listener() {
    this(XToolsClientJNI.new_Listener(), true);
  }

}
