/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class Log {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Log(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Log obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_Log(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void Info(String message) {
    XToolsClientJNI.Log_Info(message);
  }

  public static void Warning(String message) {
    XToolsClientJNI.Log_Warning(message);
  }

  public static void Error(String message) {
    XToolsClientJNI.Log_Error(message);
  }

  public Log() {
    this(XToolsClientJNI.new_Log(), true);
  }

}
