/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public enum LogSeverity {
  Info,
  Warning,
  Error;

  public final int swigValue() {
    return swigValue;
  }

  public static LogSeverity swigToEnum(int swigValue) {
    LogSeverity[] swigValues = LogSeverity.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (LogSeverity swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + LogSeverity.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private LogSeverity() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private LogSeverity(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private LogSeverity(LogSeverity swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

