/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class LogWriter {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected LogWriter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(LogWriter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_LogWriter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XToolsClientJNI.LogWriter_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XToolsClientJNI.LogWriter_change_ownership(this, swigCPtr, true);
  }

  public void WriteLogEntry(LogSeverity severity, String message) {
    if (getClass() == LogWriter.class) XToolsClientJNI.LogWriter_WriteLogEntry(swigCPtr, this, severity.swigValue(), message); else XToolsClientJNI.LogWriter_WriteLogEntrySwigExplicitLogWriter(swigCPtr, this, severity.swigValue(), message);
  }

  public LogWriter() {
    this(XToolsClientJNI.new_LogWriter(), true);
    XToolsClientJNI.LogWriter_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
