/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public enum MessagePriority {
  Immediate(0),
  High,
  Medium,
  Low;

  public final int swigValue() {
    return swigValue;
  }

  public static MessagePriority swigToEnum(int swigValue) {
    MessagePriority[] swigValues = MessagePriority.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (MessagePriority swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + MessagePriority.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private MessagePriority() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private MessagePriority(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private MessagePriority(MessagePriority swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

