/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public enum MessageChannel {
  Default(0),
  Mouse,
  Avatar,
  Audio,
  ProfileChannel,
  UserMessageChannelStart(16),
  MessageChannelMax(31);

  public final int swigValue() {
    return swigValue;
  }

  public static MessageChannel swigToEnum(int swigValue) {
    MessageChannel[] swigValues = MessageChannel.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (MessageChannel swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + MessageChannel.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private MessageChannel() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private MessageChannel(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private MessageChannel(MessageChannel swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

