/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public enum MessageID {
  Start(134),
  StatusOnly(Start),
  Broadcast,
  SessionStatus,
  SessionControl,
  MouseXToClient,
  MouseXToServer,
  SyncMessage,
  Tunnel,
  TunnelControl,
  AudioSamples,
  Handshake,
  UserPresenceChange,
  AvatarBroadcast,
  TestAutomation,
  Profiling,
  UserMessageIDStart(134+50);

  public final int swigValue() {
    return swigValue;
  }

  public static MessageID swigToEnum(int swigValue) {
    MessageID[] swigValues = MessageID.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (MessageID swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + MessageID.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private MessageID() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private MessageID(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private MessageID(MessageID swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

