/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class NetworkOutMessage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NetworkOutMessage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NetworkOutMessage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_NetworkOutMessage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Write(byte value) {
    XToolsClientJNI.NetworkOutMessage_Write__SWIG_0(swigCPtr, this, value);
  }

  public void Write(short value) {
    XToolsClientJNI.NetworkOutMessage_Write__SWIG_1(swigCPtr, this, value);
  }

  public void Write(int value) {
    XToolsClientJNI.NetworkOutMessage_Write__SWIG_2(swigCPtr, this, value);
  }

  public void Write(long value) {
    XToolsClientJNI.NetworkOutMessage_Write__SWIG_3(swigCPtr, this, value);
  }

  public void Write(float value) {
    XToolsClientJNI.NetworkOutMessage_Write__SWIG_4(swigCPtr, this, value);
  }

  public void Write(double value) {
    XToolsClientJNI.NetworkOutMessage_Write__SWIG_5(swigCPtr, this, value);
  }

  public void Write(XString value) {
    XToolsClientJNI.NetworkOutMessage_Write__SWIG_6(swigCPtr, this, XString.getCPtr(value), value);
  }

  public void WriteArray(byte[] data, long length) {
    XToolsClientJNI.NetworkOutMessage_WriteArray(swigCPtr, this, data, length);
  }

  public void Reset() {
    XToolsClientJNI.NetworkOutMessage_Reset(swigCPtr, this);
  }

}
