/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class NetworkConnectionListener extends Listener {
  private long swigCPtr;

  protected NetworkConnectionListener(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.NetworkConnectionListener_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NetworkConnectionListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_NetworkConnectionListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XToolsClientJNI.NetworkConnectionListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XToolsClientJNI.NetworkConnectionListener_change_ownership(this, swigCPtr, true);
  }

  public void OnConnected(NetworkConnection connection) {
    if (getClass() == NetworkConnectionListener.class) XToolsClientJNI.NetworkConnectionListener_OnConnected(swigCPtr, this, NetworkConnection.getCPtr(connection), connection); else XToolsClientJNI.NetworkConnectionListener_OnConnectedSwigExplicitNetworkConnectionListener(swigCPtr, this, NetworkConnection.getCPtr(connection), connection);
  }

  public void OnConnectFailed(NetworkConnection connection) {
    if (getClass() == NetworkConnectionListener.class) XToolsClientJNI.NetworkConnectionListener_OnConnectFailed(swigCPtr, this, NetworkConnection.getCPtr(connection), connection); else XToolsClientJNI.NetworkConnectionListener_OnConnectFailedSwigExplicitNetworkConnectionListener(swigCPtr, this, NetworkConnection.getCPtr(connection), connection);
  }

  public void OnDisconnected(NetworkConnection connection) {
    if (getClass() == NetworkConnectionListener.class) XToolsClientJNI.NetworkConnectionListener_OnDisconnected(swigCPtr, this, NetworkConnection.getCPtr(connection), connection); else XToolsClientJNI.NetworkConnectionListener_OnDisconnectedSwigExplicitNetworkConnectionListener(swigCPtr, this, NetworkConnection.getCPtr(connection), connection);
  }

  public void OnMessageReceived(NetworkConnection connection, NetworkInMessage message) {
    if (getClass() == NetworkConnectionListener.class) XToolsClientJNI.NetworkConnectionListener_OnMessageReceived(swigCPtr, this, NetworkConnection.getCPtr(connection), connection, NetworkInMessage.getCPtr(message), message); else XToolsClientJNI.NetworkConnectionListener_OnMessageReceivedSwigExplicitNetworkConnectionListener(swigCPtr, this, NetworkConnection.getCPtr(connection), connection, NetworkInMessage.getCPtr(message), message);
  }

  public NetworkConnectionListener() {
    this(XToolsClientJNI.new_NetworkConnectionListener(), true);
    XToolsClientJNI.NetworkConnectionListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
