/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class ObjectElementListener extends Listener {
  private long swigCPtr;

  protected ObjectElementListener(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.ObjectElementListener_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectElementListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_ObjectElementListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XToolsClientJNI.ObjectElementListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XToolsClientJNI.ObjectElementListener_change_ownership(this, swigCPtr, true);
  }

  public void OnIntElementChanged(long elementID, int newValue) {
    if (getClass() == ObjectElementListener.class) XToolsClientJNI.ObjectElementListener_OnIntElementChanged(swigCPtr, this, elementID, newValue); else XToolsClientJNI.ObjectElementListener_OnIntElementChangedSwigExplicitObjectElementListener(swigCPtr, this, elementID, newValue);
  }

  public void OnFloatElementChanged(long elementID, float newValue) {
    if (getClass() == ObjectElementListener.class) XToolsClientJNI.ObjectElementListener_OnFloatElementChanged(swigCPtr, this, elementID, newValue); else XToolsClientJNI.ObjectElementListener_OnFloatElementChangedSwigExplicitObjectElementListener(swigCPtr, this, elementID, newValue);
  }

  public void OnStringElementChanged(long elementID, XString newValue) {
    if (getClass() == ObjectElementListener.class) XToolsClientJNI.ObjectElementListener_OnStringElementChanged(swigCPtr, this, elementID, XString.getCPtr(newValue), newValue); else XToolsClientJNI.ObjectElementListener_OnStringElementChangedSwigExplicitObjectElementListener(swigCPtr, this, elementID, XString.getCPtr(newValue), newValue);
  }

  public void OnElementAdded(Element element) {
    if (getClass() == ObjectElementListener.class) XToolsClientJNI.ObjectElementListener_OnElementAdded(swigCPtr, this, Element.getCPtr(element), element); else XToolsClientJNI.ObjectElementListener_OnElementAddedSwigExplicitObjectElementListener(swigCPtr, this, Element.getCPtr(element), element);
  }

  public void OnElementDeleted(Element element) {
    if (getClass() == ObjectElementListener.class) XToolsClientJNI.ObjectElementListener_OnElementDeleted(swigCPtr, this, Element.getCPtr(element), element); else XToolsClientJNI.ObjectElementListener_OnElementDeletedSwigExplicitObjectElementListener(swigCPtr, this, Element.getCPtr(element), element);
  }

  public ObjectElementListener() {
    this(XToolsClientJNI.new_ObjectElementListener(), true);
    XToolsClientJNI.ObjectElementListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
