/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class ObjectElement extends Element {
  private long swigCPtr;

  protected ObjectElement(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.ObjectElement_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ObjectElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_ObjectElement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static ObjectElement Cast(Element element) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ObjectElement_Cast(Element.getCPtr(element), element);
    return (cPtr == 0) ? null : new ObjectElement(cPtr, true);
  }

  public IntElement CreateIntElement(XString name, int value) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ObjectElement_CreateIntElement(swigCPtr, this, XString.getCPtr(name), name, value);
    return (cPtr == 0) ? null : new IntElement(cPtr, true);
  }

  public FloatElement CreateFloatElement(XString name, float value) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ObjectElement_CreateFloatElement(swigCPtr, this, XString.getCPtr(name), name, value);
    return (cPtr == 0) ? null : new FloatElement(cPtr, true);
  }

  public StringElement CreateStringElement(XString name, XString value) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ObjectElement_CreateStringElement(swigCPtr, this, XString.getCPtr(name), name, XString.getCPtr(value), value);
    return (cPtr == 0) ? null : new StringElement(cPtr, true);
  }

  public ObjectElement CreateObjectElement(XString name, User owner) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ObjectElement_CreateObjectElement__SWIG_0(swigCPtr, this, XString.getCPtr(name), name, User.getCPtr(owner), owner);
    return (cPtr == 0) ? null : new ObjectElement(cPtr, true);
  }

  public ObjectElement CreateObjectElement(XString name) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ObjectElement_CreateObjectElement__SWIG_1(swigCPtr, this, XString.getCPtr(name), name);
    return (cPtr == 0) ? null : new ObjectElement(cPtr, true);
  }

  public int GetElementCount() {
    return XToolsClientJNI.ObjectElement_GetElementCount(swigCPtr, this);
  }

  public Element GetElement(long id) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ObjectElement_GetElement__SWIG_0(swigCPtr, this, id);
    return (cPtr == 0) ? null : new Element(cPtr, true);
  }

  public Element GetElement(XString name) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ObjectElement_GetElement__SWIG_1(swigCPtr, this, XString.getCPtr(name), name);
    return (cPtr == 0) ? null : new Element(cPtr, true);
  }

  public Element GetElementAt(int index) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.ObjectElement_GetElementAt(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Element(cPtr, true);
  }

  public void RemoveElement(Element element) {
    XToolsClientJNI.ObjectElement_RemoveElement__SWIG_0(swigCPtr, this, Element.getCPtr(element), element);
  }

  public void RemoveElement(long id) {
    XToolsClientJNI.ObjectElement_RemoveElement__SWIG_1(swigCPtr, this, id);
  }

  public void RemoveElementAt(int index) {
    XToolsClientJNI.ObjectElement_RemoveElementAt(swigCPtr, this, index);
  }

  public void AddListener(ObjectElementListener newListener) {
    XToolsClientJNI.ObjectElement_AddListener(swigCPtr, this, ObjectElementListener.getCPtr(newListener), newListener);
  }

  public void RemoveListener(ObjectElementListener oldListener) {
    XToolsClientJNI.ObjectElement_RemoveListener(swigCPtr, this, ObjectElementListener.getCPtr(oldListener), oldListener);
  }

  public long GetOwnerID() {
    return XToolsClientJNI.ObjectElement_GetOwnerID(swigCPtr, this);
  }

}
