/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class PairingManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected PairingManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PairingManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_PairingManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean HasPairingInfo() {
    return XToolsClientJNI.PairingManager_HasPairingInfo(swigCPtr, this);
  }

  public void ClearPairingInfo() {
    XToolsClientJNI.PairingManager_ClearPairingInfo(swigCPtr, this);
  }

  public boolean BeginConnecting(PairingListener listener) {
    return XToolsClientJNI.PairingManager_BeginConnecting(swigCPtr, this, PairingListener.getCPtr(listener), listener);
  }

  public void CancelConnecting() {
    XToolsClientJNI.PairingManager_CancelConnecting(swigCPtr, this);
  }

  public PairingResult BeginPairing(PairMaker pairMaker, PairingListener listener) {
    return PairingResult.swigToEnum(XToolsClientJNI.PairingManager_BeginPairing(swigCPtr, this, PairMaker.getCPtr(pairMaker), pairMaker, PairingListener.getCPtr(listener), listener));
  }

  public void CancelPairing() {
    XToolsClientJNI.PairingManager_CancelPairing(swigCPtr, this);
  }

  public boolean IsPairing() {
    return XToolsClientJNI.PairingManager_IsPairing(swigCPtr, this);
  }

  public boolean IsConnected() {
    return XToolsClientJNI.PairingManager_IsConnected(swigCPtr, this);
  }

}
