/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public enum PairingResult {
  Ok(0),
  CanceledByUser,
  FailedToOpenIncomingConnection,
  FailedToOpenOutgoingConnection,
  PairingAlreadyInProgress,
  ConnectionFailed,
  NoAddressToConnectTo;

  public final int swigValue() {
    return swigValue;
  }

  public static PairingResult swigToEnum(int swigValue) {
    PairingResult[] swigValues = PairingResult.class.getEnumConstants();
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (PairingResult swigEnum : swigValues)
      if (swigEnum.swigValue == swigValue)
        return swigEnum;
    throw new IllegalArgumentException("No enum " + PairingResult.class + " with value " + swigValue);
  }

  @SuppressWarnings("unused")
  private PairingResult() {
    this.swigValue = SwigNext.next++;
  }

  @SuppressWarnings("unused")
  private PairingResult(int swigValue) {
    this.swigValue = swigValue;
    SwigNext.next = swigValue+1;
  }

  @SuppressWarnings("unused")
  private PairingResult(PairingResult swigEnum) {
    this.swigValue = swigEnum.swigValue;
    SwigNext.next = this.swigValue+1;
  }

  private final int swigValue;

  private static class SwigNext {
    private static int next = 0;
  }
}

