/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class PairingListener extends Listener {
  private long swigCPtr;

  protected PairingListener(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.PairingListener_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(PairingListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_PairingListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XToolsClientJNI.PairingListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XToolsClientJNI.PairingListener_change_ownership(this, swigCPtr, true);
  }

  public void PairingConnectionSucceeded() {
    if (getClass() == PairingListener.class) XToolsClientJNI.PairingListener_PairingConnectionSucceeded(swigCPtr, this); else XToolsClientJNI.PairingListener_PairingConnectionSucceededSwigExplicitPairingListener(swigCPtr, this);
  }

  public void PairingConnectionFailed(PairingResult reason) {
    if (getClass() == PairingListener.class) XToolsClientJNI.PairingListener_PairingConnectionFailed(swigCPtr, this, reason.swigValue()); else XToolsClientJNI.PairingListener_PairingConnectionFailedSwigExplicitPairingListener(swigCPtr, this, reason.swigValue());
  }

  public PairingListener() {
    this(XToolsClientJNI.new_PairingListener(), true);
    XToolsClientJNI.PairingListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
