/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class ProfileManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ProfileManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ProfileManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_ProfileManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void BeginRange(String name) {
    XToolsClientJNI.ProfileManager_BeginRange(swigCPtr, this, name);
  }

  public void EndRange() {
    XToolsClientJNI.ProfileManager_EndRange(swigCPtr, this);
  }

  public void Log(LogSeverity severity, String message) {
    XToolsClientJNI.ProfileManager_Log(swigCPtr, this, severity.swigValue(), message);
  }

}
