/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class Profile {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Profile(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Profile obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_Profile(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void BeginRange(String name) {
    XToolsClientJNI.Profile_BeginRange(name);
  }

  public static void EndRange() {
    XToolsClientJNI.Profile_EndRange();
  }

  public Profile() {
    this(XToolsClientJNI.new_Profile(), true);
  }

}
