/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class Receipt {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Receipt(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Receipt obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_Receipt(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Clear() {
    XToolsClientJNI.Receipt_Clear(swigCPtr, this);
  }

  public Receipt() {
    this(XToolsClientJNI.new_Receipt(), true);
  }

}
