/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class SessionManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected SessionManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SessionManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_SessionManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void AddListener(SessionManagerListener newListener) {
    XToolsClientJNI.SessionManager_AddListener(swigCPtr, this, SessionManagerListener.getCPtr(newListener), newListener);
  }

  public void RemoveListener(SessionManagerListener oldListener) {
    XToolsClientJNI.SessionManager_RemoveListener(swigCPtr, this, SessionManagerListener.getCPtr(oldListener), oldListener);
  }

  public boolean CreateSession(XString sessionName) {
    return XToolsClientJNI.SessionManager_CreateSession(swigCPtr, this, XString.getCPtr(sessionName), sessionName);
  }

  public int GetSessionCount() {
    return XToolsClientJNI.SessionManager_GetSessionCount(swigCPtr, this);
  }

  public Session GetSession(int index) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.SessionManager_GetSession(swigCPtr, this, index);
    return (cPtr == 0) ? null : new Session(cPtr, true);
  }

  public Session GetCurrentSession() {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.SessionManager_GetCurrentSession(swigCPtr, this);
    return (cPtr == 0) ? null : new Session(cPtr, true);
  }

  public User GetCurrentUser() {
	// ref_ptr by reference javaout
    long cPtr = XToolsClientJNI.SessionManager_GetCurrentUser(swigCPtr, this);
    return (cPtr == 0) ? null : new User(cPtr, true);
  }

  public boolean IsServerConnected() {
    return XToolsClientJNI.SessionManager_IsServerConnected(swigCPtr, this);
  }

}
