/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class SessionListener extends Listener {
  private long swigCPtr;

  protected SessionListener(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.SessionListener_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SessionListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_SessionListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XToolsClientJNI.SessionListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XToolsClientJNI.SessionListener_change_ownership(this, swigCPtr, true);
  }

  public void OnJoiningSession() {
    if (getClass() == SessionListener.class) XToolsClientJNI.SessionListener_OnJoiningSession(swigCPtr, this); else XToolsClientJNI.SessionListener_OnJoiningSessionSwigExplicitSessionListener(swigCPtr, this);
  }

  public void OnJoinSucceeded() {
    if (getClass() == SessionListener.class) XToolsClientJNI.SessionListener_OnJoinSucceeded(swigCPtr, this); else XToolsClientJNI.SessionListener_OnJoinSucceededSwigExplicitSessionListener(swigCPtr, this);
  }

  public void OnJoinFailed() {
    if (getClass() == SessionListener.class) XToolsClientJNI.SessionListener_OnJoinFailed(swigCPtr, this); else XToolsClientJNI.SessionListener_OnJoinFailedSwigExplicitSessionListener(swigCPtr, this);
  }

  public void OnSessionDisconnected() {
    if (getClass() == SessionListener.class) XToolsClientJNI.SessionListener_OnSessionDisconnected(swigCPtr, this); else XToolsClientJNI.SessionListener_OnSessionDisconnectedSwigExplicitSessionListener(swigCPtr, this);
  }

  public SessionListener() {
    this(XToolsClientJNI.new_SessionListener(), true);
    XToolsClientJNI.SessionListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
