/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class Session {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Session(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Session obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_Session(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public MachineSessionState GetMachineSessionState() {
    return MachineSessionState.swigToEnum(XToolsClientJNI.Session_GetMachineSessionState(swigCPtr, this));
  }

  public void AddListener(SessionListener newListener) {
    XToolsClientJNI.Session_AddListener(swigCPtr, this, SessionListener.getCPtr(newListener), newListener);
  }

  public void RemoveListener(SessionListener oldListener) {
    XToolsClientJNI.Session_RemoveListener(swigCPtr, this, SessionListener.getCPtr(oldListener), oldListener);
  }

  public boolean IsJoined() {
    return XToolsClientJNI.Session_IsJoined(swigCPtr, this);
  }

  public boolean Join() {
    return XToolsClientJNI.Session_Join(swigCPtr, this);
  }

  public void Leave() {
    XToolsClientJNI.Session_Leave(swigCPtr, this);
  }

  public int GetUserCount() {
    return XToolsClientJNI.Session_GetUserCount(swigCPtr, this);
  }

  public User GetUser(int i) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.Session_GetUser(swigCPtr, this, i);
    return (cPtr == 0) ? null : new User(cPtr, true);
  }

  public SessionType GetSessionType() {
    return SessionType.swigToEnum(XToolsClientJNI.Session_GetSessionType(swigCPtr, this));
  }

  public XString GetName() {
	// ref_ptr by reference javaout
    long cPtr = XToolsClientJNI.Session_GetName(swigCPtr, this);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

  public NetworkConnection GetSessionNetworkConnection() {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.Session_GetSessionNetworkConnection(swigCPtr, this);
    return (cPtr == 0) ? null : new NetworkConnection(cPtr, true);
  }

}
