/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class Settings {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Settings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Settings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_Settings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Settings() {
    this(XToolsClientJNI.new_Settings(), true);
  }

  public XString GetServerAddress() {
	// ref_ptr by reference javaout
    long cPtr = XToolsClientJNI.Settings_GetServerAddress(swigCPtr, this);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

  public int GetServerPort() {
    return XToolsClientJNI.Settings_GetServerPort(swigCPtr, this);
  }

  public XString GetViewerAddress() {
	// ref_ptr by reference javaout
    long cPtr = XToolsClientJNI.Settings_GetViewerAddress(swigCPtr, this);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

  public int GetViewerPort() {
    return XToolsClientJNI.Settings_GetViewerPort(swigCPtr, this);
  }

  public XString GetLocalUserName() {
	// ref_ptr by reference javaout
    long cPtr = XToolsClientJNI.Settings_GetLocalUserName(swigCPtr, this);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

}
