/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class StringElement extends Element {
  private long swigCPtr;

  protected StringElement(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.StringElement_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringElement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_StringElement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static StringElement Cast(Element element) {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.StringElement_Cast(Element.getCPtr(element), element);
    return (cPtr == 0) ? null : new StringElement(cPtr, true);
  }

  public XString GetValue() {
	// ref_ptr by reference javaout
    long cPtr = XToolsClientJNI.StringElement_GetValue(swigCPtr, this);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

  public void SetValue(XString newString) {
    XToolsClientJNI.StringElement_SetValue(swigCPtr, this, XString.getCPtr(newString), newString);
  }

}
