/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class SyncListener extends Listener {
  private long swigCPtr;

  protected SyncListener(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.SyncListener_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(SyncListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_SyncListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XToolsClientJNI.SyncListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XToolsClientJNI.SyncListener_change_ownership(this, swigCPtr, true);
  }

  public void OnSyncChangesBegin() {
    if (getClass() == SyncListener.class) XToolsClientJNI.SyncListener_OnSyncChangesBegin(swigCPtr, this); else XToolsClientJNI.SyncListener_OnSyncChangesBeginSwigExplicitSyncListener(swigCPtr, this);
  }

  public void OnSyncChangesEnd() {
    if (getClass() == SyncListener.class) XToolsClientJNI.SyncListener_OnSyncChangesEnd(swigCPtr, this); else XToolsClientJNI.SyncListener_OnSyncChangesEndSwigExplicitSyncListener(swigCPtr, this);
  }

  public SyncListener() {
    this(XToolsClientJNI.new_SyncListener(), true);
    XToolsClientJNI.SyncListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
