/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class TagImage {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected TagImage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(TagImage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_TagImage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public int GetWidth() {
    return XToolsClientJNI.TagImage_GetWidth(swigCPtr, this);
  }

  public int GetHeight() {
    return XToolsClientJNI.TagImage_GetHeight(swigCPtr, this);
  }

  public void CopyImageData(byte[] data, int bufferSize, int bytesPerPixel) {
    XToolsClientJNI.TagImage_CopyImageData(swigCPtr, this, data, bufferSize, bytesPerPixel);
  }

}
