/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class User {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected User(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(User obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_User(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XString GetName() {
	// ref_ptr by reference javaout
    long cPtr = XToolsClientJNI.User_GetName(swigCPtr, this);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

  public long GetID() {
    return XToolsClientJNI.User_GetID(swigCPtr, this);
  }

  public boolean IsValid() {
    return XToolsClientJNI.User_IsValid(swigCPtr, this);
  }

  public boolean GetMuteState() {
    return XToolsClientJNI.User_GetMuteState(swigCPtr, this);
  }

  public final static long kInvalidUserID = 0xFFFFFFFFL;
}
