/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class UserPresenceManager {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected UserPresenceManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UserPresenceManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_UserPresenceManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void AddListener(UserPresenceManagerListener newListener) {
    XToolsClientJNI.UserPresenceManager_AddListener(swigCPtr, this, UserPresenceManagerListener.getCPtr(newListener), newListener);
  }

  public void RemoveListener(UserPresenceManagerListener oldListener) {
    XToolsClientJNI.UserPresenceManager_RemoveListener(swigCPtr, this, UserPresenceManagerListener.getCPtr(oldListener), oldListener);
  }

  public boolean GetMuteState() {
    return XToolsClientJNI.UserPresenceManager_GetMuteState(swigCPtr, this);
  }

  public void SetMuteState(boolean muteState) {
    XToolsClientJNI.UserPresenceManager_SetMuteState(swigCPtr, this, muteState);
  }

  public void SetName(XString name) {
    XToolsClientJNI.UserPresenceManager_SetName(swigCPtr, this, XString.getCPtr(name), name);
  }

  public XString GetName() {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.UserPresenceManager_GetName(swigCPtr, this);
    return (cPtr == 0) ? null : new XString(cPtr, true);
  }

  public void SetUser(User localUser) {
    XToolsClientJNI.UserPresenceManager_SetUser(swigCPtr, this, User.getCPtr(localUser), localUser);
  }

}
