/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class UserPresenceManagerListener extends Listener {
  private long swigCPtr;

  protected UserPresenceManagerListener(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.UserPresenceManagerListener_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(UserPresenceManagerListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_UserPresenceManagerListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    XToolsClientJNI.UserPresenceManagerListener_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    XToolsClientJNI.UserPresenceManagerListener_change_ownership(this, swigCPtr, true);
  }

  public void OnUserPresenceChanged(User user) {
    if (getClass() == UserPresenceManagerListener.class) XToolsClientJNI.UserPresenceManagerListener_OnUserPresenceChanged(swigCPtr, this, User.getCPtr(user), user); else XToolsClientJNI.UserPresenceManagerListener_OnUserPresenceChangedSwigExplicitUserPresenceManagerListener(swigCPtr, this, User.getCPtr(user), user);
  }

  public UserPresenceManagerListener() {
    this(XToolsClientJNI.new_UserPresenceManagerListener(), true);
    XToolsClientJNI.UserPresenceManagerListener_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
