/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class VisualPairReceiver extends PairMaker {
  private long swigCPtr;

  protected VisualPairReceiver(long cPtr, boolean cMemoryOwn) {
    super(XToolsClientJNI.VisualPairReceiver_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VisualPairReceiver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_VisualPairReceiver(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public static VisualPairReceiver Create() {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.VisualPairReceiver_Create();
    return (cPtr == 0) ? null : new VisualPairReceiver(cPtr, true);
  }

  public TagImage CreateTagImage() {
	// ref_ptr by value javaout
    long cPtr = XToolsClientJNI.VisualPairReceiver_CreateTagImage(swigCPtr, this);
    return (cPtr == 0) ? null : new TagImage(cPtr, true);
  }

}
