/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class XString {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected XString(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XString obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        XToolsClientJNI.delete_XString(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XString() {
    this(XToolsClientJNI.new_XString__SWIG_0(), true);
  }

  public XString(String str) {
    this(XToolsClientJNI.new_XString__SWIG_1(str), true);
  }

  public long GetLength() {
    return XToolsClientJNI.XString_GetLength(swigCPtr, this);
  }

  public boolean IsEqual(XString otherStr) {
    return XToolsClientJNI.XString_IsEqual(swigCPtr, this, XString.getCPtr(otherStr), otherStr);
  }

  public String GetString() {
    return XToolsClientJNI.XString_GetString(swigCPtr, this);
  }

}
