/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.microsoft.xtools;

public class XToolsClient {
  public static java.math.BigInteger getKInvalidSocketID() {
    return XToolsClientJNI.kInvalidSocketID_get();
  }

  public static java.math.BigInteger getKInvalidConnectionGUID() {
    return XToolsClientJNI.kInvalidConnectionGUID_get();
  }

  public static long getKInvalidXGuid() {
    return XToolsClientJNI.kInvalidXGuid_get();
  }

}
