name: '$(date:yyMM).$(date:dd)$(rev:rr)-${{ parameters.Project }}'

parameters:
- name: Sign
  type: boolean
  default: false
- name: Project
  type: string
  default: PlaneFinding
  values:
    - MicStreamSelector
    - PlaneFinding
    # - GpuStats

# Don't automatically run this pipeline
trigger: none
pr: none

extends:
  template: Templates/pipeline.yml
  parameters:
    ProjectFriendlyName: ${{ parameters.Project }}
    Sign: ${{ parameters.Sign }}
    ${{ if eq(parameters.Project, 'MicStreamSelector') }}:
      SolutionPath: Input/MicStreamSelector/Solutions/MicStreamSelector.sln
      BuildOutputPath: Input/MicStreamSelector/Solutions/Release
      UnityFolderPath: Input/MicStreamSelector/UnityAddon
    ${{ if eq(parameters.Project, 'PlaneFinding') }}:
      SolutionPath: SpatialMapping/PlaneFinding/PlaneFinding.sln
      BuildOutputPath: SpatialMapping/PlaneFinding/Release
      UnityFolderPath: SpatialMapping/PlaneFinding/UnityAddon
    ${{ if eq(parameters.Project, 'GpuStats') }}:
      SolutionPath: GpuStats/GpuStats.sln
      BuildOutputPath: GpuStats/BuildOutput/bin/Release
      UnityFolderPath: GpuStats/UnityAddon
