/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace HoloToolkit.XTools {

public class PairingManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PairingManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PairingManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PairingManager() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XToolsClientPINVOKE.delete_PairingManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool HasPairingInfo() {
    bool ret = XToolsClientPINVOKE.PairingManager_HasPairingInfo(swigCPtr);
    return ret;
  }

  public virtual void ClearPairingInfo() {
    XToolsClientPINVOKE.PairingManager_ClearPairingInfo(swigCPtr);
  }

  public virtual bool BeginConnecting(PairingListener listener) {
    bool ret = XToolsClientPINVOKE.PairingManager_BeginConnecting(swigCPtr, PairingListener.getCPtr(listener));
    return ret;
  }

  public virtual void CancelConnecting() {
    XToolsClientPINVOKE.PairingManager_CancelConnecting(swigCPtr);
  }

  public virtual PairingResult BeginPairing(PairMaker pairMaker, PairingListener listener) {
    PairingResult ret = (PairingResult)XToolsClientPINVOKE.PairingManager_BeginPairing(swigCPtr, PairMaker.getCPtr(pairMaker), PairingListener.getCPtr(listener));
    return ret;
  }

  public virtual void CancelPairing() {
    XToolsClientPINVOKE.PairingManager_CancelPairing(swigCPtr);
  }

  public virtual bool IsPairing() {
    bool ret = XToolsClientPINVOKE.PairingManager_IsPairing(swigCPtr);
    return ret;
  }

  public virtual bool IsConnected() {
    bool ret = XToolsClientPINVOKE.PairingManager_IsConnected(swigCPtr);
    return ret;
  }

}

}
