/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace HoloToolkit.XTools {

public class VisualPairConnector : PairMaker {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal VisualPairConnector(global::System.IntPtr cPtr, bool cMemoryOwn) : base(XToolsClientPINVOKE.VisualPairConnector_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(VisualPairConnector obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~VisualPairConnector() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          XToolsClientPINVOKE.delete_VisualPairConnector(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public static VisualPairConnector Create() {
    global::System.IntPtr cPtr = XToolsClientPINVOKE.VisualPairConnector_Create();
    VisualPairConnector ret = (cPtr == global::System.IntPtr.Zero) ? null : new VisualPairConnector(cPtr, true);
    return ret; 
  }

  public unsafe bool ProcessImage(byte[] image, int width, int height, int bytesPerPixel) {
    fixed ( byte* swig_ptrTo_image = image ) {
    {
      bool ret = XToolsClientPINVOKE.VisualPairConnector_ProcessImage(swigCPtr, (global::System.IntPtr)swig_ptrTo_image, width, height, bytesPerPixel);
      return ret;
    }
    }
  }

  public virtual bool IsProcessingImage() {
    bool ret = XToolsClientPINVOKE.VisualPairConnector_IsProcessingImage(swigCPtr);
    return ret;
  }

}

}
